version: "3.8"
services:
  db:
    image: mysql
    platform: linux/x86_64
    networks:
      - infovisnet
    environment:
      - MYSQL_ROOT_PASSWORD=vidim
      - MYSQL_DATABASE=dblp_behaviors
  web:
    container_name: scholartree
    build: .
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/code
    networks:
      - infovisnet
    depends_on: # to control startup order
      - db


networks:
  infovisnet:
    name: infovisnet