version: "3.8"
services:
  db:
    image: mysql
    ports:
      - "3306:3306" # think about 'expose' - then mysql is only avail through linked services like 'web'
    environment:
      - MYSQL_ROOT_PASSWORD=vidim
      - MYSQL_DATABASE=dblp_behaviors
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000" # change in production environment - kwon might use this one
    depends_on: # to control startup order
      - db
